version: '3.8'

services:
  go-tic-tac-toe:
    image: pakasfand/go-tic-tac-toe:latest
    container_name: go-tic-tac-toe-app
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
    networks:
      - tic-tac-toe-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  nginx:
    image: nginx:alpine
    container_name: tic-tac-toe-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - go-tic-tac-toe
    networks:
      - tic-tac-toe-network

networks:
  tic-tac-toe-network:
    driver: bridge
